---
- name: Start service couchbase-server, if not started
  service:
    name: mongod
    state: started

# V-81843 # V-81883 # V-81889 # V-81891 # V-81895
- name: Verify MongoDB config file -security
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^#security:$'
    line: ' '

- name: Verify MongoDB config file -security
  blockinfile: 
    path: '/etc/mongod.conf'
    insertafter: " "
    block: |4
        security: 
          authorization: enabled
          enableEncryption: true
          javascriptEnabled: false
          redactClientLogData: true

# V-81845

# V-81847  
- name: Check if configuration file contains key auditlog
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^#auditLog:$'
    line: ' '

- name: Check if configuration file contains key auditlog and filter
  blockinfile:
    path: /etc/mongod.conf
    marker: ' '
    insertafter: “ ”
    block: |4
        auditLog: 
          destination: syslog
          filter: '{ atype: { $in: [ \"createCollection\", \"dropCollection\" ] } }'
 
# V-81849 V-81851 # V-81887
- name: verify User ownership, Group ownership, and permssions
  file:
    path: /var/lib/mongo/
    owner: mongod
    group: mongod
    mode: '700'

# V-81857
- name: Uninstall unused packages
  yum:
    name: 
      - enterprise-shell
      - enterprise-mongos
      - enterprise-tools
    state: absent

# V-81861 # V-81875 # V-81869 # V-81879
- name: Remove occurances of invalid certs
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^# network interfaces$'
    line: ' '

- name: Remove occurances of invalid certs
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^net:$'
    line: ' '

- name: Remove occurances of invalid certs
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^  port: 27017$'
    line: ' '

- name: Remove occurances of invalid certs
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^  bindIp: 127.0.0.1  # Listen to local interface only, comment to listen on all interfaces.$'
    line: ' '

- name: Remove occurances of invalid certs
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^allowInvalidCertificates: true$'
    line: ' '

- name: Remove occurances false fipsmode
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^FIPSMode: false$'
    line: ' '

- name: Verify MongoDB config file
  blockinfile:
    path: /etc/mongod.conf
    marker: '  '
    insertafter: “# network interfaces”
    block: |4
        # network interfaces
        net:
          http:
            enabled: false
            JSONPEnabled: false
            RESTInterfaceEnabled: false
          ssl:
            FIPSMode: true
            mode: requireSSL
            PEMKeyFile: /etc/ssl/mongodb.pem
            CAFile: /etc/ssl/mongodbca.pem

# V-81863

# V-81865

# V-81867

# V-81871
- name: verify User ownership, Group ownership, and permssions
  file:
    path: /etc/mongod.conf
    state: touch
    mode: u+rw,g-rwx,o-rwx

- name: Change file ownership, group and permissions
  file:
    path: /etc/mongod.conf
    owner: mongod
    group: mongod

# V-81873

# V-81877

# V-81881
- name: Remove occurances of nojournal
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^--nojournal$'
    line: ' '

# V-81899

# V-81901

# V-81903
- name: Enable auditing
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^# Where and how to store data.$'
    line: ' '

- name: Enable auditing
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^storage:$'
    line: ' '

- name: Enable auditing
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^  dbPath: /var/lib/mongo$'
    line: ' '

- name: Enable auditing
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^  journal:$'
    line: ' '

- name: Enable auditing
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: '^    enabled: true$'
    line: ' '

- name: Enable auditing
  blockinfile:
    path: /etc/mongod.conf
    marker: '  '
    insertafter: “^# Where and how to store data.”
    block: |4
        # Where and how to store data.
        storage:
          dbPath: data/db
        auditLog:
          destination: syslog
          path: 

# V-81905

# V-81907

# V-81909

# V-81911

# V-81917

# V-81919 #####need more work?
- name: Enable encryption 
  blockinfile:
    path: /etc/mongod.conf
    marker: '  '
    insertafter: “ ”
    block: |
      --enableEncryption
      --kmipServerName <KMIP Server HostName>
      --kmipPort <KMIP server port>
      --kmipServerCAFile ca.pem
      --kmipClientCertificateFile client.pem
