---
- name: Start service mongodb-server, if not started
  service:
    name: mongod
    state: started

# V=81917 or are we supposed to generate one to pass the control?
- name: generate self-signed ssl certificate and key
  shell: "openssl x509 -in /etc/ssl/mongodb.pem -text | grep -i 'issuer'"
  changed_when: 1

# V-81919
- name: set KMIP settings for data at rest encryption
  lineinfile:
    path: '/etc/mongod.conf'
    regexp: "(|#)enableEncryption:.*"
    line: "  enableEncryption: true"
    insertafter: "^security:$"
  blockinfile:
    path: '/etc/mongod.conf'
    marker: "# {mark} KMIP config"
    insertafter: "^security:$"
    block: |2
        kmip:
          serverName: server.ip
          port: 5696
          clientCertificateFile: /etc/ssl/mongodb_kmip_client.pem
          serverCAFile: /etc/ssl/mongodb_kmip_ca.pem

# V-81923 
- name: set SSL as required with custom key file
  blockinfile:
    path: '/etc/mongod.conf'
    marker: "# {mark} SSL config"
    insertafter: "^net:$"
    block: |2
        ssl:
          mode: requireSSL
          certificateKeyFile: /etc/ssl/mongodb.pem
