- name: Start service mongodb-server, if not started
  service:
    name: mongod
    state: started

# V-81843
- name: enable security
  lineinfile:
    path: "{{ mongod_conf }}"
    regexp: '^#security:$'
    line: 'security:'
- name: set authorization enabled
  lineinfile:
    path: "{{ mongod_conf }}"
    regexp: "(|#)authorization:.*"
    line: "  authorization: enabled"
    insertafter: "^security:$"

# V-81849 V-81887
- name: secure access to mongo directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '700'
    owner: mongod
    group: mongod
  with_items:
    - /var/lib/mongo/
    - /data/db/

# V-81851
- name: secure access to config file
  file:
    path: "{{ mongod_conf }}"
    mode: u+rw,g-rwx,o-rwx
    owner: mongod
    group: mongod

# V-81871
- name: secure access to SSL certs
  file:
    path: "{{ item }}"
    state: touch
    mode: u+rw,g-rwx,o-rwx
    owner: mongod
    group: mongod
  with_items:
      - /etc/ssl/mongodbca.pem
      - /etc/ssl/mongodb.pem
      - /etc/ssl/mongodb_kmip_client.pem
      - /etc/ssl/mongodb_kmip_ca.pem

# V-81859
- name: uninstall unused packages
  yum:
    name: 
      - mongodb-enterprise-mongos
      - mongodb-enterprise-shell
      - mongodb-enterprise-tools
    state: absent

# V-81861
# this needs to be null for 3.6

# V-81881
# storage journal already enabled by default

# V-81867
- name: set certificate authenticaion mode
  lineinfile:
    path: "{{ mongod_conf }}"
    regexp: "(|#)clusterAuthMode:.*"
    line: "  clusterAuthMode: x509"
    insertafter: "^security:$"

# V-81879 V-81921 V-81923 V-81869
- name: set SSL as required with custom key file
  blockinfile:
    path: "{{ mongod_conf }}"
    marker: "# {mark} SSL config"
    insertafter: "^net:$"
    block: |2
        ssl:
          mode: requireSSL
          PEMKeyFile: /etc/ssl/mongodb.pem
          CAFile: /etc/ssl/mongodbca.pem
# V-81875
- name: enable NIST FIPS 140-2-validated cryptographic modules
  lineinfile:
    path: "{{ mongod_conf }}"
    regexp: "(|#)FIPSMode:.*"
    line: "    FIPSMode: true"
    insertafter: "^ +ssl:$"

# V-81883
- name: enable MongoDB Encrypted Storage Engine
  lineinfile:
    path: "{{ mongod_conf }}"
    regexp: "(|#)enableEncryption:.*"
    line: "  enableEncryption: true"
    insertafter: "^security:$"

# V-81891 V-81889
- name: disable the use of javascript
  lineinfile:
    path: "{{ mongod_conf }}"
    regexp: "(|#)javascriptEnabled:.*"
    line: "  javascriptEnabled: false"
    insertafter: "^security:$"

# V-81895
- name: redact sensative data in log file
  lineinfile:
    path: "{{ mongod_conf }}"
    regexp: "(|#)redactClientLogData:.*"
    line: "  redactClientLogData: true"
    insertafter: "^security:$"

# V-81847 V-81901 V-81905 V-81907 
- name: set audit log destination
  lineinfile:
    path: "{{ mongod_conf }}"
    regexp: ".*auditLog:.*\n.*destination:.*"
    line: "auditLog:\n  destination: syslog"

# V-81903
- name: set path of database files
  lineinfile:
    path: "{{ mongod_conf }}"
    regexp: ".*dbPath:.*"
    line: "  dbPath: data/db"
    insertafter: "^storage:$"

# V-81917
- name: generate self-signed ssl certificate and key
  shell: |
    openssl req -nodes -x509 -newkey rsa:2048 -keyout /tmp/ca.key -out /tmp/ca.crt -subj "/C=US/ST=DC/L=GOV/O=DoD/OU=root/CN=MONGODB/emailAddress=ansible@mongodb.config"
    openssl req -nodes -newkey rsa:2048 -keyout /tmp/server.key -out /tmp/server.csr -subj "/C=US/ST=DC/L=GOV/O=DoD/OU=server/CN=MONGODB/emailAddress=ansible@mongodb.config"
    openssl x509 -req -in /tmp/server.csr -CA /tmp/ca.crt -CAkey /tmp/ca.key -CAcreateserial -out /tmp/server.crt
    cat /tmp/server.key /tmp/server.crt > /etc/ssl/mongodb.pem
    cat /tmp/ca.crt > /etc/ssl/mongodbca.pem
    cp /etc/ssl/mongodb.pem /etc/ssl/mongodb_kmip_client.pem
    cp /etc/ssl/mongodbca.pem /etc/ssl/mongodb_kmip_ca.pem
  changed_when: 1

# V-81919 not working
#- name: set KMIP settings for data at rest encryption
 # blockinfile:
  #  path: "{{ mongod_conf }}"
   # marker: "# {mark} KMIP config"
    #insertafter: "^security:$"
    #block: |2
     #   kmip:
      #    serverName: server.ip
       #   port: 5696
        #  clientCertificateFile: /etc/ssl/mongodb_kmip_client.pem
         # serverCAFile: /etc/ssl/mongodb_kmip_ca.pem
  #notify: restart mongod

# V-81845, V-81857, V-81863, V-81877, V-81899, V-81909, V-81911
- name: Create MongoDB Admin user 
  mongodb_user:
    database: "admin"
    name: "mongodb_admin"
    password: "mongodb_admin"
    roles: "userAdminAnyDatabase"

- name: Create MongoDB Regular user 
  mongodb_user:
    database: "admin"
    name: "mongoadmin"
    password: "mongoadmin"
    roles: "userAdminAnyDatabase"


# V-81865
#TODO ldap auth check



