- hosts: localhost
  tasks:
    - name: Start service mongodb-server, if not started
      service:
        name: mongod
        state: started

    - name: Create MongoDB Admin user 
      mongodb_user:
        database: "admin"
        name: "mongodb_admin"
        password: "mongodb_admin"
        roles: "userAdminAnyDatabase"

    - name: Create MongoDB Regular user 
      mongodb_user:
        database: "admin"
        name: "mongoadmin"
        password: "mongoadmin"
        roles: "userAdminAnyDatabase"
